### ISSUE TITLE
Consider adding LICENSE file

### ISSUE THREAD

**Issue by spacem** [TimLuq/wsdl-to-ts#5]
Hi, this is a pretty neat little project but I notice you don't have any license. Please can you confirm is it ok to use it without restriction to produce interfaces that are used in commercial software?

One little suggestion is for me I prefer all the members of the interfaces to be optional but I just did find/replace for `:` and replace with `?:` so not important.

**Comment by TimLuq** [comment]
The license is specified in the package.json as ISC. Which according to nodejs doesn't need an explicit license file since it is a registered license. But, yes I'll add an additional license file in the future.

License is basically: 
- If you use it internally as a CLI tool you may do whatever.
- If you publish a project using the lib to npm the dependency in your package.json is enough.
- If you bundle code from the project and and ship it to users a reference/link to the license/project must be made accessible to the users (for example visible from an About view).

v1 has plans to use optional properties when appropriate according to the schema.
